@local-host = http://localhost:8080
@shop-code = shop-code

### 매장 테이블 조회
GET {{local-host}}/management/shop/{{shop-code}}

### 매장 등록
POST {{local-host}}/management/shop
Content-Type: application/json

{
    "shop": {
        "code": "{{shop-code}}",
        "name": "매장 이름"
    }
}

### 카테고리 등록
POST {{local-host}}/management/category
Content-Type: application/json

{
    "shopCode": "{{shop-code}}",
    "categoryList": [
        {
            "code": "category-1",
            "name": "카테고리1"
        },
        {
            "code": "category-2",
            "parentCategoryCode": "category-a",
            "name": "카테고리2"
        },
      {
        "code": "category-3",
        "parentCategoryCode": "category-2",
        "name": "카테고리2"
      }
    ]
}

### 상품 등록
POST {{local-host}}/management/item
Content-Type: application/json

{
    "shopCode": "{{shop-code}}",
    "itemList": [
        {
            "categoryCode": "category-1",
            "code": "item-1",
            "name": "아이템-1!",
            "price": 3.45
        },
        {
            "categoryCode": "category-2",
            "code": "item-5",
            "name": "아이템-5",
            "price": 3.47
        },
        {
            "categoryCode": "category-3",
            "code": "item-7",
            "name": "아이템-7",
            "price": 3.46
        }
    ]
}

### 옵션 등록
POST {{local-host}}/management/option
Content-Type: application/json

{
    "shopCode": "{{shop-code}}",
    "optionList": [
        {
            "itemCode": "item-1",
            "code": "option-1",
            "name": "옵션-1",
            "type": "RADIO"
        },
        {
            "itemCode": "item-1",
            "code": "option-2",
            "name": "옵션-2",
            "type": "RADIO"
        },
        {
            "itemCode": "item-1",
            "code": "option-3",
            "name": "옵션-3"
        }
    ]
}

### 옵션값 등록
POST {{local-host}}/management/option-value
Content-Type: application/json

{
    "shopCode": "{{shop-code}}",
    "optionValueList": [
        {
            "optionCode": "option-1",
            "code": "value-1",
            "name": "엘리먼트-1",
            "price": 3.45
        },
        {
            "optionCode": "option-2",
            "code": "value-2",
            "name": "엘리먼트-2"
        },
        {
            "optionCode": "option-2",
            "code": "value-3"
        }
    ]
}
