spring:
  application:
    name: shoplatform

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shoplatform?useUnicode=true&characterEncoding=utf8
    username: root
    password: password

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false